throwErrorOnExtraParameters: true

resourceBundle: Report

templates:
    A4 portrait: !template
        reportTemplate: pdfextract.jrxml
        outputFilename: ${yyyyMMddhhmmss}_extract
        attributes:
            CreationDate: !string {}
            Signature: !string &optStr
                default: ''
            ConcernedTheme: !datasource
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            NotConcernedTheme: !datasource
                default:
                  - Code: 'Code not concerned'
                    Text: 'Theme theme not concerned'
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            ThemeWithoutData: !datasource
                default:
                  - Code: 'Code without data'
                    Text: 'Theme without data'
                attributes:
                    Code: !string {}
                    Text: !string {} #/definitions/LocalisedText
            isReduced: !boolean {}
            LogoPLRCadastre: !string
              default: ""
            LogoPLRCadastreRef: *optStr
            FederalLogo: !string
              default: ""
            FederalLogoRef: *optStr
            CantonalLogo: !string
              default: ""
            CantonalLogoRef: *optStr
            MunicipalityLogo: *optStr
            MunicipalityLogoRef: *optStr
            ExtractIdentifier: !string {}
            QRCode: *optStr
            QRCodeRef: *optStr
            GeneralInformation: !string #/definitions/MultilingualMText
                default: 'Disclaimer'
            BaseData: !string {} #/definitions/MultilingualMText
            Glossary: !datasource
                default:
                  - Title: 'No term'
                    Content: 'No definition'
                attributes:
                    Title: !string {} #/definitions/MultilingualText
                    Content: !string {} #/definitions/MultilingualText
            RealEstate_Number: !string {}
            RealEstate_IdentDN: !string {}
            RealEstate_EGRID: !string {}
            RealEstate_Type: !string {}
            RealEstate_Canton: !string {}
            RealEstate_Municipality: !string {}
            RealEstate_SubunitOfLandRegister: !string
                default: ''
            RealEstate_FosNr: !string {}
            RealEstate_MetadataOfGeographicalBaseData: !string
                default: ''
            RealEstate_LandRegistryArea: !string {}
            RealEstate_Limit: !string #/definitions/MultiSurface"
                default: '{}'
            RealEstate_RestrictionOnLandownership: !datasource
                default: []
                attributes:
                    Legend: !datasource
                        attributes:
                            TypeCode: !string #/definitions/RestrictiontypeCode
                                default: ''
                            TypeCodelist: !string
                                default: ''
                            Area: !string #/definitions/Area
                                default: ''
                            PartInPercent: !float
                                default: -1
                            Length: !float
                                default: -1
                            SymbolRef: !string
                                default: ''
                            Information: !string #/definitions/MultilingualMText
                                default: ''
                    Geom_Type: !string {}
                    Theme_Code: !string
                        default: ''
                    Theme_Text: !string #/definitions/LocalisedText
                        default: ''
                    SubTheme: !string
                        default: ''
                    Lawstatus_Code: *optStr
                    Lawstatus_Text: *optStr #/definitions/LocalisedText
                    Symbol: !string
                        default: ''
                    Geometry: !datasource
                        default: []
                        attributes:
                            Point: !string {} #/definitions/PointPropertyType
                            Line: !string {} #/definitions/CurvePropertyType
                            Surface: !string {} #/definitions/SurfacePropertyType
                            Lawstatus: !string {} #/definitions/Lawstatus
                            MetadataOfGeographicalBaseData: !string {}
                            ResponsibleOffice_Name: !string {} #/definitions/MultilingualText
                            ResponsibleOffice_OfficeAtWeb: !string {} #/definitions/WebReference
                            ResponsibleOffice_UID: *optStr #/definitions/UID
                            ResponsibleOffice_Line1: *optStr
                            ResponsibleOffice_Line2: *optStr
                            ResponsibleOffice_Street: *optStr
                            ResponsibleOffice_Number: *optStr
                            ResponsibleOffice_PostalCode: *optStr
                            ResponsibleOffice_City: *optStr

                    legend: !string {}
                    map: !map
                        maxDpi: 254
                        dpiSuggestions: [254]
                        zoomLevels: !zoomLevels
                            scales: [100, 250, 500, 2500, 5000, 10000, 25000, 50000, 100000, 500000]
                        width: 493
                        height: 280
                        default:
                            projection: "EPSG:2056"
                            dpi: 72
                            zoomToFeatures:
                                minScale: 500
                    baseLayers: !staticLayers {}

                    ResponsibleOffice_Name: !string #/definitions/MultilingualText
                        default: ''
                    ResponsibleOffice_OfficeAtWeb: !string #/definitions/WebReference
                        default: ''
                    ResponsibleOffice_UID: !string #/definitions/UID
                        default: ''
                    ResponsibleOffice_Line1: !string
                        default: ''
                    ResponsibleOffice_Line2: !string
                        default: ''
                    ResponsibleOffice_Street: !string
                        default: ''
                    ResponsibleOffice_Number: !string
                        default: ''
                    ResponsibleOffice_PostalCode: !string
                        default: ''
                    ResponsibleOffice_City: !string
                        default: ''
                    LegalProvisions: !datasource
                        default: []
                        attributes: &lpra
                            TextAtWeb: !string {} #/definitions/MultilingualUri
                            Lawstatus_Code: *optStr
                            Lawstatus_Text: *optStr #/definitions/LocalisedText
                            Number: *optStr #/definitions/ArticleNumber
                            Text: *optStr #/definitions/MultilingualMText
                            Title: *optStr #/definitions/MultilingualText
                            OfficialTitle: *optStr #/definitions/MultilingualText
                            Abbrevation: *optStr #/definitions/MultilingualText
                            OfficialNumber: *optStr
                            Canton: *optStr #/definitions/CantonCode
                            Municipality: *optStr #/definitions/MunicipalityCode
                            ResponsibleOffice_Name: !string {} #/definitions/MultilingualText
                            ResponsibleOffice_OfficeAtWeb: !string {} #/definitions/WebReference
                            ResponsibleOffice_UID: *optStr #/definitions/UID
                            ResponsibleOffice_Line1: *optStr
                            ResponsibleOffice_Line2: *optStr
                            ResponsibleOffice_Street: *optStr
                            ResponsibleOffice_Number: *optStr
                            ResponsibleOffice_PostalCode: *optStr
                            ResponsibleOffice_City: *optStr
                            OfficialNumber: *optStr #/definitions/CantonCode
                            ArticleNumber: *optStr #array of /definitions/ArticleNumber
                    Reference: !datasource
                        default: []
                        attributes: *lpra
                    Article: !datasource
                        default: []
                        attributes: *lpra
            ExclusionOfLiability: !datasource
                default: []
                attributes:
                    Title: !string {} #/definitions/MultilingualText
                    Content: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_Name: !string {} #/definitions/MultilingualText
            PLRCadastreAuthority_OfficeAtWeb: !string {} #/definitions/WebReference
            PLRCadastreAuthority_UID: !string #/definitions/UID
                default: ''
            PLRCadastreAuthority_Line1: !string
                default: ''
            PLRCadastreAuthority_Line2: !string
                default: ''
            PLRCadastreAuthority_Street: !string {}
            PLRCadastreAuthority_Number: !string {}
            PLRCadastreAuthority_PostalCode: !string {}
            PLRCadastreAuthority_City: !string {}

            northArrow: !northArrow
                size: 17
                default:
                    graphic: "file:///north.svg"
            scalebar: !scalebar
                width: 100
                height: 15
                default:
                     fontSize: 7
            features: !features {}
            map: !map
                maxDpi: 254
                dpiSuggestions: [254]
                zoomLevels: !zoomLevels
                    scales: [100, 250, 500, 2500, 5000, 10000, 25000, 50000, 100000, 500000]
                width: 493
                height: 280
                default:
                    projection: "EPSG:2056"
                    dpi: 72
                    zoomToFeatures:
                        minScale: 500
            baseLayers: !staticLayers {}
            overlayLayers: !staticLayers
                default:
                    layers:
                    -   type: geoJson
            style: !style
                default:
                    style:
                        version: 2
                        '*':
                            symbolizers:
                            -   type: polygon
                                fillColor: "#ff0000"
                                fillOpacity: 0.1
                                strokeColor: "#660000"
                                strokeOpacity: 1
                                strokeWidth: 2
                                strokeLinecap: "round"

        processors:
        - !reportBuilder # compile all reports in current directory
            directory: '.'
        - !configureHttpRequests
            httpProcessors:
            - !mapUri    # NEEDED FOR DOCKER ENVIRONMENT
                mapping:
                  (https?)://localhost:6543/(.*): "http://wsgi/$2"
            - !forwardHeaders
                headers:
                - Referer
            - !restrictUris
                matchers:
                - !dnsMatch    # NEEDED FOR DOCKER ENVIRONMENT
                  host: wsgi
                  port: 80
                  reject: false
                - !ipMatch
                  ip: 10.0.0.0
                  mask: 255.0.0.0
                  reject: true
                - !ipMatch
                  ip: 172.16.0.0
                  mask: 255.240.0.0
                  reject: true
                - !ipMatch
                  ip: 192.168.0.0
                  mask: 255.255.0.0
                  reject: true
                - !acceptAll {}
        - !addOverlayLayers
            inputMapper:
                overlayLayers: staticLayers
        - !addBackgroundLayers
            inputMapper:
                baseLayers: staticLayers
        - !setStyle {}
        - !setFeatures {}
        - !createMap {}
        - !createNorthArrow {}
        - !createScalebar {}
        - !createDataSource
            processors: []
            inputMapper:
                ConcernedTheme: datasource
            outputMapper:
                jrDataSource: ConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                NotConcernedTheme: datasource
            outputMapper:
                jrDataSource: NotConcernedThemeDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ThemeWithoutData: datasource
            outputMapper:
                jrDataSource: ThemeWithoutDataDataSource
        - !createDataSource
            processors: []
            inputMapper:
                Glossary: datasource
            outputMapper:
                jrDataSource: GlossaryDataSource
        - !createDataSource
            copyAttributes: [overlayLayers, style, features]
            processors:
            - !createDataSource
                processors: []
                inputMapper:
                    Legend: datasource
                outputMapper:
                    jrDataSource: LegendDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    Geometry: datasource
                outputMapper:
                    jrDataSource: GeometryDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    LegalProvisions: datasource
                outputMapper:
                    jrDataSource: LegalProvisionsDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    Reference: datasource
                outputMapper:
                    jrDataSource: ReferenceDataSource
            - !createDataSource
                processors: []
                inputMapper:
                    Article: datasource
                outputMapper:
                    jrDataSource: ArticleDataSource
            - !addOverlayLayers
                inputMapper:
                    overlayLayers: staticLayers
            - !addBackgroundLayers
                inputMapper:
                    baseLayers: staticLayers
            - !setStyle {}
            - !setFeatures {}
            - !createMap {}
            inputMapper:
                RealEstate_RestrictionOnLandownership: datasource
            outputMapper:
                jrDataSource: RealEstate_RestrictionOnLandownershipDataSource
        - !createDataSource
            processors: []
            inputMapper:
                ExclusionOfLiability: datasource
            outputMapper:
                jrDataSource: ExclusionOfLiabilityDataSource
