name: Daily deploy to Pypi
on:
   schedule:
     - cron: "15 07 * * *"
jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build/wheel
      run: >-
        python -m
        pip install
        build
        wheel
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py
        egg_info
        --tag-date
        --tag-build=dev
        sdist
        bdist_wheel
    # - name: Publish distribution ðŸ“¦ to PyPI
    #   uses: pypa/gh-action-pypi-publish@master
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}
  doc:
    name: Make and deploy documentation
    runs-on: ubuntu-20.04
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Make and publish doc
        env:
          PYTHON_VERSION: python3.7
        run: |
          sudo apt-get install virtualenv libpq-dev libgeos-dev
          make install
          .venv/bin/pip install sphinxcontrib-versioning 'Sphinx<1.6' mako sphinx_rtd_theme --editable .[recommend]
          make doc
          git config --global user.name "c2c-bot-gis-ci"
          git config --global user.email "c2c-bot-gis-ci@users.noreply.github.com"
          git remote set-url --push origin "git@github.com:openoereb/pyramid_oereb.git"
          source .venv/bin/activate && sphinx-versioning push doc/source gh-pages doc
