name: Daily deploy to Pypi
on:
   schedule:
     - cron: "45 07 * * *"
jobs:
  deploy-dev:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build/wheel
      run: >-
        python -m
        pip install
        build
        wheel
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python setup.py
        egg_info
        --tag-date
        --tag-build=dev
        sdist
        bdist_wheel
    - name: Publish distribution ðŸ“¦ to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build documentation ðŸ“–
      run: |
          sudo apt-get install virtualenv libpq-dev libgeos-dev
          make doc
    - name: Deploy ðŸš€ documentation to GitHub pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: doc # The folder the action should deploy.
